---
title: "Economist Chart Replication"
author: "Taehwan Kim"
date: "4/11/2019"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(ggthemes)
library(tidyverse)

download.file(url = "http://infographics.economist.com/databank/Economist_corbyn.csv",
              destfile = "likes.csv",
              mode = "wb")

likes <- read_csv("likes.csv", 
                  col_types = cols(
                                   Page = col_character(),
                                   `Average number of likes per Facebook post 2016` = col_double())) %>% 
  filter(!is.na(`Average number of likes per Facebook post 2016`))

```

```{r replication}

likes %>% 
  ggplot(aes(x = reorder(Page,  `Average number of likes per Facebook post 2016`), y = `Average number of likes per Facebook post 2016`)) +
  geom_col() +
  coord_flip() +
  theme_economist() +
  labs(title = "Left-click",
       subtitle = "Average number of likes per Facebook post 2016, '000",
       caption = "Source: Facebook") +
  xlab("") +
  ylab("") +
  scale_y_continuous(position = "right", 
                     breaks = seq(0, 6000, 1000), 
                     labels = c("0", "1", "2", "3", "4", "5", "6")) +
  theme(line = element_blank(),
        panel.grid.minor = element_line(colour = "white",size=0.75), legend.position = "none")

```

